### PR TITLE
0.0.16 release (User auto-complete)

### LINKED ISSUE #16: Update pass-indexer to support both the ES completion suggester and the pass modified completion suggester
Perform necessary update to pass-indexer so that it can work with user objects being suggested using the regular ES completion suggester AND the journal object being suggested using the  pass modified completion suggester .

MOre details in this discussion document

### PR DESCRIPTION
**Pull request by markpatton**
This release update the mapping to automatically add a "suggest_person" field to objects which contains the result of combining "firstName", "lastName", "displayName", and "email" attributes. A "type" context is set on the field with the value of the "@type" attribute.

Only objects which contain one of those attributes will have a "suggest_person" field added. That seems to be Contributor and User. The values are treated as keywords with case ignored. (This is important for email completion to work nicely.) The name "suggest_person" is mean to distinguish it from native fields and exempt it from the special handling of "NAME_suggest" as well as indicate that a person related object is being suggested. Is there a better naming scheme? This seems confusing given the NAME_suggest handling. 

The "suggest_person" field can be used with the completion service just like journalName_suggest. Note that the "suggest_person" field is produced entirely by the mapping, not by any action of pass-indexer as with NAME_suggest.

In order to test, try out pass-indexer on a fresh Elasticsearch, push User records to Fedora and call the completion service with something like the below. Note the request has a context which is restricting matches to User objects and that only 5 matches are returned by default.

 ```
curl 'http://localhost:9200/pass/_search?pretty' -H 'Content-Type: application/json; charset=UTF-8' --data-binary '
 {
    "suggest": {
        "mysuggest": {
            "prefix": "bes",
            "completion": {
                "field": "suggest_person",
                "context": {"type": "User"}
            }
        }
    }
}'
```
You can use the docker-composer setup for ITs to make testing this simpler. Just `docker-compose up`, wait for it to settle, and then 'mvn verify', After that finishes there will be some User records and Contributor records. Do 'curl http://localhost:9200/pass/_search' to see all of them.

Do various searches and check that expected objects match.

When we are happy, I will release the cli on github.

Closes #16

### CODE REVIEW

**Comment by htpvu** [comment]
@markpatton `suggest-person` sounds good. 

So does the fact that this field exists for both Contributor and User mean that when suggestions are made, they are made with matching Contributor objects AND matching User objects? Or can the suggestions be filter by type?

**Comment by markpatton** [comment]
The suggestions will come from both object types. Remember in Elasticsearch these are all just documents.

In order to filter, you would have to add a category to each suggest field which distinguished the documents based on something like the value of @type. (I actually did this in an earlier version of the auto-complete support.) Then when using the completion service the client specifies a category to restrict the completions.

**Comment by karenhanson** [comment]
@markpatton @htpvu I agree wrt `suggest-person`. 
We definitely will need to filter out `Contributor` data for the user search - we made a conscious decision that `Contributor` would be messy and potentially have a lot of redundancy. Is another change required in order to make that possible? Or would that be done in Ember?

**Comment by markpatton** [comment]
@karenhanson 
Yes.  Adding categories is work for the indexer, but then the pass-ember completion service will need work.

**Comment by htpvu** [comment]
@markpatton Please add support for filtering by type to the indexer.

**Comment by karenhanson** [comment]
Tested - it works exactly as described - but I'm wondering if we need to revisit how we want this to work.
 
I had an offline discussion with Mark . Currently the completion suggestion search matches one of `lastName`, `firstName`, `email`, `displayName` based on "prefix". The example we discussed was:
```
firstName: Karen
lastName: Hanson
displayName: Cassy Hanson
email: kh@example.com
```
* If they search `Kar` they will get all Users where one of these fields matches `kar*` (case insensitive) including the above record. 
* If they type `Karen`, it will match the above record based on `firstName` and any other Users where any of the fields start with `karen*` - potentially a lot. 
* If they then type `Karen Hanson`, they will get no results, because this does not match any one field. 
Note that, if the display name was `Karen Hanson`, this would return the correct record.
* If they type `Hanson` it will work if there are less than 5 in the database - typing `Hanson Karen` will return nothing.

We need to discuss whether we are OK with those constraints, or if it should behave differently - I have a mock up of what I consider to be the perfect result, which may or may not be plausible.

**Comment by karenhanson** [comment]
After further discussion, we are going in a different direction with this integration. Will close this for now.

**Pull request closed without merging**
